docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
      - all-globs-to-all-files:
          - '!src/**'
          - '!tests/**'
          - '!benchmarking/**'
          - '!.github/**'
          - '!.gitignore'
          - '!package.json'
          - '!bun.lock'
          - '!*.config.{js,ts}'
          - '!*.json'

internal:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - .gitignore
          - .prettierignore
          - .prettierrc
          - .npmrc
      - all-globs-to-all-files:
          - '!**/*.md'
          - '!src/**'
          - '!tests/**'
          - '!benchmarking/**'

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*.{yml,yaml}'

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.ts'

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.js'

svelte:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.svelte'

bun:
  - changed-files:
      - any-glob-to-any-file:
          - 'bun.lock'
